#!/bin/bash
date=`date +%d-%m-%y-%H-%M`
<%= oracle_bin_path %>/expdp "<%= db_user %>/<%= db_pass %> schemas=<%= schema %> directory=<%= directory %> dumpfile=<%= dumpfile %>-$date.dmp" && bzip2 <%= dumpdirectory %>/<%= dumpfile %>-$date.dmp
