#!/bin/bash
date
<%= oracle_bin_path %>/sqlplus -SILENT  <%= db_user %>/<%= db_pass %> <% if sysdba %>as sysdba<% end %> <<- END_SQL
set feedback off
SET HEAD ON
SET colsep ';'
SET PAGESIZE 0
SET LINESIZE 3270
SET CONCAT ON

<%= sql %>

END_SQL
date
